In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
muertes = pd.read_csv('def17cont.csv')

In [6]:
muertes.head()

ENT_REGIS  MUN_REGIS  ENT_RESID  MUN_RESID  TLOC_RESID  LOC_RESID  \
0          1          1          1          1          15          1   
1          1          9          1          9           1         16   
2          1          1          1          1          15          1   
3          1          6          1          6           8          1   
4          1          1          1          1          15          1   

   ENT_OCURR  MUN_OCURR  TLOC_OCURR  LOC_OCUR  ... MATERNAS LENGUA  COND_ACT  \
0          1          1          15         1  ...      NaN      9         2   
1          1          9           1        16  ...      NaN      9         2   
2          1          1          15         1  ...      NaN      9         1   
3          1          6           8         1  ...      NaN      2         2   
4          1          1          15         1  ...      NaN      9         1   

   PAR_AGRE  ENT_OCULES  MUN_OCULES  LOC_OCULES  RAZON_M  DIS_RE_OAX  \
0        88          88         888        8888      NaN         999   
1        88          88         888        8888      NaN         999   
2        88          88         888        8888      NaN         999   
3        88          88         888        8888      NaN         999   
4        88          88         888        8888      NaN         999   

   CONTADOR   
0          1  
1          1  
2          1  
3          1  
4          1  

[5 rows x 60 columns]

In [7]:
maximo = muertes['CAUSA_DEF'].value_counts()
print(maximo)

I219    92555
E119    31077
E112    27620
J189    17202
K746    15387
        ...  
Q642        1
M799        1
D337        1
B450        1
P100        1
Name: CAUSA_DEF, Length: 3948, dtype: int64


In [8]:
maximo1 = maximo.head(3)

In [31]:
fig = plt.figure(figsize=(100,100))
maximo1.plot(kind='bar')
plt.xticks(range (3), fontsize=60, rotation='horizontal')
plt.bar(range(3),maximo1, align='center', color=['blue','red','green'])
plt.title("Principales causas de muerte en México durante 2017", fontsize=100)
plt.xlabel("")
plt.ylabel(" ")
plt.yticks(fontsize=60)

(array([     0.,  20000.,  40000.,  60000.,  80000., 100000.]),
 [Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, '')])

In [34]:
I219 = muertes[muertes['CAUSA_DEF']=='I219']
E119 = muertes[muertes['CAUSA_DEF']=='E119']
E112 = muertes[muertes['CAUSA_DEF']=='E112']
#print(I219['ENT_REGIS'].value_counts(ascending=True))
#print(E119['ENT_REGIS'].value_counts(ascending=True))
#print(E112['ENT_REGIS'].value_counts(ascending=True))

In [35]:
I219_1 = I219['ENT_REGIS'].value_counts(ascending=True)
E119_1 = E119['ENT_REGIS'].value_counts(ascending=True)
E112_1 = E112['ENT_REGIS'].value_counts(ascending=True)
I219_2 = I219_1.tail(3)
E119_2 = E119_1.tail(3)
E112_2 = E112_1.tail(3)

In [39]:
fig = plt.figure(figsize=(100,100))
I219_2.plot(kind='bar')
plt.bar(range(3),I219_2, align='center', color=['yellow','brown','purple'])
plt.xticks(range(3), fontsize=60, rotation='horizontal')
plt.title("Estados con mayor incidencia de muertes por Infarto agudo del miocardio, sin otra especificación", fontsize=100)
plt.xlabel("")
plt.ylabel(" ")
plt.yticks(fontsize=60)

(array([    0.,  2000.,  4000.,  6000.,  8000., 10000., 12000.]),
 [Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, '')])

In [40]:
fig = plt.figure(figsize=(100,100))
E119_2.plot(kind='bar')
plt.bar(range(3),E119_2, align='center', color=['gray','olive','cyan'])
plt.xticks(range(3), fontsize=60, rotation='horizontal')
plt.title("Estados con mayor incidencia de muertes por Diabetes mellitus no insulinodependiente, sin mención de complicación", fontsize=100)
plt.xlabel("")
plt.ylabel(" ")
plt.yticks(fontsize=60)

(array([   0.,  500., 1000., 1500., 2000., 2500., 3000., 3500., 4000.]),
 [Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, '')])

In [41]:
fig = plt.figure(figsize=(100,100))
E112_2.plot(kind='bar')
plt.bar(range(3),E112_2, align='center', color=['teal','gold','crimson'])
plt.xticks(range(3), fontsize=60, rotation='horizontal')
plt.title("Estados con mayor incidencia de muertes por Diabetes mellitus no insulinodependiente, con complicaciones renales", fontsize=100)
plt.xlabel("")
plt.ylabel(" ")
plt.yticks(fontsize=60)

(array([   0.,  500., 1000., 1500., 2000., 2500., 3000., 3500., 4000.,
        4500.]),
 [Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, '')])